language: php

php:
  - '7.1'

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_ENV=dev

before_script:
  - cp app/config/parameters-travis.yml app/config/parameters.yml
  - composer install --no-progress --no-interaction --prefer-dist --no-suggest
  - mysql -e 'CREATE DATABASE website_cms;'

script:
  - php bin/console doctrine:schema:create
  - php bin/console doctrine:fixtures:load -n
  - vendor/bin/codecept run

notifications:
  webhooks:
    urls:
      - https://www.vivifyscrum.com/ciintegrations/travis/7dd62d610592e999fe5df424a5250e22
