version: "3"

services:
  app:
    image: webdevops/php-apache:7.2
    ports:
      - "10000:80"
    depends_on:
      - db
    environment:
      WEB_DOCUMENT_ROOT: /srv/web
      WEB_DOCUMENT_INDEX: app.php
      PHP_DATE_TIMEZONE: "UTC"
    working_dir: /srv
    volumes:
      - .:/srv

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: website_cms
      MYSQL_USER: website
      MYSQL_PASSWORD: website
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "10001:3306"
