<?php

namespace AppBundle\Repository;

/**
 * CategoryAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryAttributeRepository extends \Doctrine\ORM\EntityRepository
{
}
