<?php

namespace AppBundle\Repository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends PublishableEntityRepository
{
    public function findLast()
    {
        return $this->createQueryBuilder('m')
            ->orderBy('m.order', 'desc')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findPublished()
    {
        return $this->createQueryBuilder('m')
            ->where('m.publishedAt <= :now')
            ->setParameter('now', new \DateTime())
            ->orderBy('m.order', 'asc')
            ->getQuery()
            ->getResult();
    }

    public function findAll()
    {
        return $this->createQueryBuilder('m')
            ->orderBy('m.order', 'asc')
            ->getQuery()
            ->getResult();
    }
}
