<?php

namespace AppBundle\Repository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends PublishableEntityRepository
{
    public function findLast()
    {
        return $this->createQueryBuilder('m')
            ->orderBy('m.order', 'desc')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
