<?php

namespace AppBundle\Repository;

/**
 * ProductPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
