<?php

namespace AppBundle\Repository;

/**
 * ProductSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
