imports:
    - { resource: parameters.yml }
    - { resource: app.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: twig_parameters.yml }

parameters:
    locale: fr
    uploads: 'uploads'

framework:
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

ivory_ck_editor:
    configs:
        my_config:
            toolbar: my_config
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters:
                instance: ckeditor
    toolbars:
        configs:
            my_config: [ "@bloc_5", "@bloc_1", "@bloc_3", "@bloc_2", "@bloc_4" ]
        items:
            bloc_1: [ 'Bold', 'Italic', 'Underline', 'Blockquote', '-', 'RemoveFormat' ]
            bloc_2: [ 'NumberedList', 'BulletedList' ]
            bloc_3: [ 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' ]
            bloc_4: [ 'Table', 'Image' ]
            bloc_5: [ 'Format', 'Source' ]

fm_elfinder:
    instances:
        ckeditor:
            locale: "%locale%"
            editor: ckeditor
            fullscreen: false
            include_assets: true
            connector:
                debug: false
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: '%uploads%'
                        upload_allow: [ 'image/png', 'image/jpg', 'image/jpeg' ]
                        upload_deny: [ 'all' ]
                        upload_max_size: 2M
