uploads:
    resource: '@AppBundle/Controller/ImageController.php'
    type: annotation

elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"
    prefix: '/admin'

admin:
    resource: '@AppBundle/Controller/Admin/'
    type: annotation
    prefix: '/admin'

client:
    resource: '@AppBundle/Controller/Client/'
    type: annotation
    prefix: '/client'

front:
    resource: '@AppBundle/Controller/Front/'
    type: annotation
    prefix: '/'

