uploads:
    resource: '@AppBundle/Controller/ImageController.php'
    type: annotation

front:
    resource: '@AppBundle/Controller/Front/'
    type: annotation
    prefix: '/'

client:
    resource: '@AppBundle/Controller/Client/'
    type: annotation
    prefix: '/client'

admin:
    resource: '@AppBundle/Controller/Admin/'
    type: annotation
    prefix: '/admin'
