security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        user:
            entity:
                class: AppBundle\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            context: website
            pattern: ^/admin
            provider: user
            anonymous: ~
            form_login:
                login_path: admin_login
                check_path: admin_login
            logout:
                path: admin_logout

        professional:
            context: website
            pattern: ^/espace-pro
            provider: user
            anonymous: ~
            form_login:
                login_path: professional_login
                check_path: professional_login_check
            logout:
                path: professional_logout

        user:
            context: website
            pattern: ^/
            provider: user
            anonymous: ~
            form_login:
                login_path: client_login
                check_path: client_login_check
                default_target_path: client_register_address
            logout:
                path: client_logout

    role_hierarchy:
        ROLE_PRO: ROLE_USER
        ROLE_ADMIN: ROLE_PRO

    access_control:
        - { path: ^/client/sign-in, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/register_email, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/front, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client, roles: "ROLE_USER" }
        - { path: ^/admin/sign-in, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: "ROLE_ADMIN" }
        - { path: ^/espace-pro/sign-in, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/espace-pro, roles: "ROLE_PRO" }
