security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        user:
            entity:
                class: AppBundle\Entity\User
                property: email
        admin:
            entity:
                class: AppBundle\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user:
            pattern: ^/
            provider: user
            anonymous: ~
            form_login:
                login_path: client_login
                check_path: client_login_check
                default_target_path: client_register_address
            logout:
                path: client_logout

        admin:
            pattern: ^/
            provider: admin
            anonymous: ~
            form_login:
                login_path: admin_login
                check_path: admin_login
            logout:
                path: admin_logout

    access_control:
        - { path: ^/client/sign-in, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/register_email, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/front, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client, roles: "ROLE_USER" }
        - { path: ^/admin/sign-in, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: "ROLE_ADMIN" }
