parameters:
    env(DATABASE_HOST): db
    env(DATABASE_PORT): null
    env(DATABASE_NAME): website_cms
    env(DATABASE_USER): website
    env(DATABASE_PASSWORD): website

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
